# Generated by Django 5.1 on 2024-09-03 20:35

import django.contrib.postgres.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NewsSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('url', models.URLField(unique=True)),
                ('reliability_score', models.FloatField(default=0.0)),
                ('political_leaning', models.CharField(choices=[('far_left', 'Far Left'), ('left', 'Left'), ('center_left', 'Center Left'), ('center', 'Center'), ('center_right', 'Center Right'), ('right', 'Right'), ('far_right', 'Far Right')], max_length=50)),
                ('country', models.CharField(max_length=100)),
                ('language', models.CharField(max_length=50)),
                ('last_scraped', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('url', models.URLField(unique=True)),
                ('author', models.CharField(blank=True, max_length=200)),
                ('published_date', models.DateTimeField()),
                ('content', models.TextField()),
                ('summary', models.TextField(blank=True)),
                ('keywords', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), blank=True, size=None)),
                ('category', models.CharField(max_length=100)),
                ('sentiment_score', models.FloatField(blank=True, null=True)),
                ('objectivity_score', models.FloatField(blank=True, null=True)),
                ('ai_generated_tags', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), blank=True, size=None)),
                ('read_time', models.IntegerField(help_text='Estimated read time in minutes')),
                ('view_count', models.IntegerField(default=0)),
                ('share_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('related_articles', models.ManyToManyField(blank=True, to='api.article')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.newssource')),
            ],
            options={
                'ordering': ['-published_date'],
            },
        ),
    ]
